project:
  type: website

website:
  title: "Blog"
  navbar:
    right:
      - icon: github
        href: https://github.com/swissjobtracker
      - icon: globe
        href: https://swissjobtracker.github.io
format:
  html:
    theme: cosmo
    css: styles.css



