project:
  type: website

website:
  title: "Swiss Job Tracker"
  site-url: https://swissjobtracker.ch
  navbar:
    left:
      - text: "Blog"
        href: /
    right:
      - icon: github
        href: https://github.com/swissjobtracker
format:
  html:
    theme: cosmo
    css: styles.css



