project:
  type: website

website:
  favicon: favicon.ico
  navbar:
    left:
      - text: "Swiss Job Tracker"
        href: https://swissjobtracker.ch
      - text: "Blog"
        href: /
    right:
      - icon: github
        href: https://github.com/swissjobtracker
format:
  html:
    theme: cosmo
    css: styles.css



